name: Laboratorio 5 - Pipeline Hibrido

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite ejecutar el pipeline manualmente

jobs:
  # Este Job se ejecuta en la nube de GitHub
  job-en-la-nube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Tarea en GitHub Hosted
        run: |
          echo "Este paso se esta ejecutando en los servidores de GitHub"
          echo "Entorno del sistema:"
          uname -a

  # Este Job se ejecuta en TU infraestructura (Self-hosted)
  job-en-mi-servidor:
    runs-on: [self-hosted, label-inexistente]
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Tarea en Self-Hosted
        run: |
          echo "Este paso se esta ejecutando localmente en MI infraestructura"
          echo "Mi usuario local es:"
          whoami
